importing the needed libraby stuff

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
import re
import joblib
import string

importing the file of data 
here we have two files :
1 > fake.csv
2 > true.csv

In [2]:
fake = pd.read_csv('Fake.csv')
true = pd.read_csv('True.csv')

C:\Users\DIPTESH\AppData\Local\Temp\ipykernel_10540\4167979911.py:1: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171) have mixed types. Specify dtype option on import or set low_memory=False.
  fake = pd.read_csv('Fake.csv')

DATA SET

In [3]:
fake.head()

,title,text,subject,date,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 162,Unnamed: 163,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,Unnamed: 168,Unnamed: 169,Unnamed: 170,Unnamed: 171
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

deopping all the unwanted columns

In [4]:
fake = pd.read_csv("Fake.csv")
fake = fake.dropna(axis=1, how="all")  

true = pd.read_csv("True.csv")
true = true.dropna(axis=1, how="all")

C:\Users\DIPTESH\AppData\Local\Temp\ipykernel_10540\1242193904.py:1: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171) have mixed types. Specify dtype option on import or set low_memory=False.
  fake = pd.read_csv("Fake.csv")

In [5]:
fake.head()

,title,text,subject,date,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 162,Unnamed: 163,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,Unnamed: 168,Unnamed: 169,Unnamed: 170,Unnamed: 171
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [7]:
fake.head()

,title,text,subject,date,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 162,Unnamed: 163,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,Unnamed: 168,Unnamed: 169,Unnamed: 170,Unnamed: 171
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
fake = pd.read_csv("Fake.csv")
fake = fake.dropna(axis=1, how="all")

C:\Users\DIPTESH\AppData\Local\Temp\ipykernel_10540\3582853259.py:1: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171) have mixed types. Specify dtype option on import or set low_memory=False.
  fake = pd.read_csv("Fake.csv")

In [9]:
fake.head()

,title,text,subject,date,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 162,Unnamed: 163,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,Unnamed: 168,Unnamed: 169,Unnamed: 170,Unnamed: 171
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [11]:
fake.head()

,title,text,subject,date,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 162,Unnamed: 163,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,Unnamed: 168,Unnamed: 169,Unnamed: 170,Unnamed: 171
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
fake = pd.read_csv("Fake.csv")
fake = fake.loc[:, ~fake.columns.str.contains('^Unnamed')]

true = pd.read_csv("True.csv")
true = true.loc[:, ~true.columns.str.contains('^Unnamed')]

C:\Users\DIPTESH\AppData\Local\Temp\ipykernel_10540\358598430.py:1: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171) have mixed types. Specify dtype option on import or set low_memory=False.
  fake = pd.read_csv("Fake.csv")

In [13]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [14]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

givin class to both the dataset and assigning 
0 for fake news
1 for true news

In [15]:
fake['class'] = 0
true['class'] = 1

here , we are concatenating two data set into one data

In [16]:
data = pd.concat([fake,true],axis= 0)

In [17]:
data.sample(10)

,title,text,subject,date,class
19730,Western powers urge Myanmar's Suu Kyi to push ...,"NEW YORK (Reuters) - Britain, France and Austr...",worldnews,"September 18, 2017",1
18195,UNIV Of GA PROFESSOR Allows Students To CHOOSE...,A University of Georgia professor has adopted ...,left-news,"Aug 8, 2017",0
14220,WATCH: HILARIOUS AD Calls Into Question Health...,"After watching this telling video, you ll wond...",politics,"Mar 24, 2016",0
17330,EU imposes oil embargo on North Korea in symbo...,LUXEMBOURG (Reuters) - The European Union bann...,worldnews,"October 16, 2017",1
23207,"‘Beyonce, Jay Z, Hillary Clinton – You Don’t R...",21st Century Wire says One of the great myths ...,Middle-east,"November 11, 2016",0
19222,BUDWEISER Unveils SUPER BOWL Ad That Distorts ...,So much for the cute little puppies and clydes...,left-news,"Feb 1, 2017",0
17858,Germany may not agree new coalition until next...,BERLIN (Reuters) - Germany may need to wait un...,worldnews,"October 10, 2017",1
21410,BREAKING: Biden Won’t Run…Is It Because Biden ...,This announcement seems to indicate that the O...,left-news,"Oct 21, 2015",0
14133,Summit on euro zone future in December still o...,BRUSSELS (Reuters) - A summit of euro zone lea...,worldnews,"November 22, 2017",1
13983,"In western Moscow, Putin allies lose an electi...",MOSCOW (Reuters) - More than 10 weeks after lo...,worldnews,"November 24, 2017",1

droping the unwanted data columns from the data

In [18]:
data = data.drop(['title','subject','date'],axis = 1)

In [19]:
data.sample(10)

                                                    text  class
5009   (Reuters) - Puerto Rico’s governor said on Sat...      1
17696  HONG KONG/BEIJING (Reuters) - China said on Th...      1
14017  Meanwhile Trump is about to make history for c...      0
14714  BEIRUT (Reuters) - France said on Wednesday th...      1
5931   WASHINGTON/MOSCOW (Reuters) - Russian Presiden...      1
7143   If you ve been privy to any form of a Donald T...      0
19110  PRAGUE (Reuters) - Britain can negotiate its e...      1
10844  WASHINGTON (Reuters) - The U.S. Senate on Frid...      1
14228  After the community found out about the threat...      0
20365  In their desire to push Hillary Clinton across...      0

reseting index of data and dropping the index

In [20]:
data.reset_index(inplace=True)

In [21]:
data.drop(['index'],axis=1 ,inplace=True)

In [22]:
data.sample(5)

                                                    text  class
29566  WASHINGTON (Reuters) - Congressional Republica...      1
32780  WASHINGTON (Reuters) - The District of Columbi...      1
2865   While Donald Trump likes to go around saying h...      0
10037  A kind woman brought Fox News reporter Casey S...      0
28044  WASHINGTON (Reuters) - U.S. President Donald T...      1

1 : convert all the text into lower case
2 : remove the text which were the enclosed in the []
3 : this regular expression for replace all the non werb character like (digits,underscores) with a space 
4 : this will remove the url's which would be stating with http or https  or domain start with www. 
5 : using this we ll remove the html tags 
6 : this will remove the punctuation marks by asccaping and matching all characters in the strings.punctuation
7 : remove the new line characters 
8 : removing words which contains digits , it can be "132sdf"

In [23]:
def clean_text(text):
    text = text.lower()         
    text = re.sub('\[.*?\]',"",text)
    text = re.sub("\\w"," ",text)
    text = re.sub("https?:://\S+|www\.\S+" "",text)
    text = re.sub("<.*?>=+","",text)
    text = re.sub("[%s]" % re.escape(string.punctuation),"",text)
    text = re.sub("\n","",text)
    text = re.sub("\w*\d\w*","",text)
    return text

<>:3: SyntaxWarning: invalid escape sequence '\['
<>:5: SyntaxWarning: invalid escape sequence '\S'
<>:9: SyntaxWarning: invalid escape sequence '\w'
<>:3: SyntaxWarning: invalid escape sequence '\['
<>:5: SyntaxWarning: invalid escape sequence '\S'
<>:9: SyntaxWarning: invalid escape sequence '\w'
C:\Users\DIPTESH\AppData\Local\Temp\ipykernel_10540\1123824662.py:3: SyntaxWarning: invalid escape sequence '\['
  text = re.sub('\[.*?\]',"",text)
C:\Users\DIPTESH\AppData\Local\Temp\ipykernel_10540\1123824662.py:5: SyntaxWarning: invalid escape sequence '\S'
  text = re.sub("https?:://\S+|www\.\S+" "",text)
C:\Users\DIPTESH\AppData\Local\Temp\ipykernel_10540\1123824662.py:9: SyntaxWarning: invalid escape sequence '\w'
  text = re.sub("\w*\d\w*","",text)

In [1]:

def clean_text(text):
    text = text.lower()
    text = re.sub(r'\[.*?\]', '', text)  # remove things in [ ]
    text = re.sub(r'https?://\S+|www\.\S+', '', text)  # remove URLs
    text = re.sub(r'<.*?>', '', text)  # remove HTML tags
    text = re.sub(r'[%s]' % re.escape(string.punctuation), '', text)  # remove punctuation
    text = re.sub(r'\n', ' ', text)  # remove newlines
    text = re.sub(r'\w*\d\w*', '', text)  # remove words with numbers
    text = re.sub(r'\W+', ' ', text)  # replace non-word chars with space
    return text.strip()

In [24]:
data.sample(5)

                                                    text  class
29624  SANTIAGO (Reuters) - Chile will continue to pu...      1
9362   On September 27, 2017, an unhinged, liberal, T...      0
5089   In another blow to voter and racial suppressio...      0
43069  PARIS (Reuters) - Four months after a heavy el...      1
17698  The move by a Twitter employee last week to ba...      0

In [25]:
data.drop("index", axis=1, inplace=True)

KeyError: "['index'] not found in axis"

In [26]:
def clean_text(text):
    text = text.lower()

    text = re.sub(r'\[.*?\]', '', text)                                        # remove things in [ ]
    text = re.sub(r'https?://\S+|www\.\S+', '', text)                          # remove URLs
    text = re.sub(r'<.*?>', '', text)                                          # remove HTML tags
    text = re.sub(r'[%s]' % re.escape(string.punctuation), '', text)           # remove punctuation
    text = re.sub(r'\n', ' ', text)                                            # remove newlines
    text = re.sub(r'\w*\d\w*', '', text)                                       # remove words with numbers
    text = re.sub(r'\W+', ' ', text)                                           # replace non-word chars with space
    return text.strip()

In [27]:
data.sample(35)

                                                    text  class
34376  WASHINGTON (Reuters) - The U.S. House of Repre...      1
26724  WASHINGTON (Reuters) - The gunshots that rippe...      1
7452   Mitt Romney watched his dream of becoming pres...      0
10413  Where was the media s outrage when a sitting U...      0
36282  BRUSSELS (Reuters) - The future free trade agr...      1
4452   Even Fox News is not pleased about Sean Hannit...      0
6255   One of Donald Trump s advisors thought he was ...      0
9511   The decision of actress Mila Kunis to make mon...      0
20109  This is a great story for anyone who doesn t u...      0
31183  WASHINGTON (Reuters) - Vice President Joe Bide...      1
28471  WASHINGTON/BOCA RATON (Reuters) - The top U.S....      1
32206  CLEVELAND (Reuters) - U.S. Senator Ted Cruz re...      1
40383  CAIRO (Reuters) - Islamic State has claimed re...      1
27330  WASHINGTON (Reuters) - A review of President D...      1
42926  MEXICO CITY (Reuters) - Mexican rescuers raced...      1
39005  JAKARTA (Reuters) - Indonesia s Constitutional...      1
17146  Obama s war against America on every possible ...      0
14855  How long do you think our  President  has know...      0
16651  The irony in Obama s radical Treasury Secretar...      0
26942  WASHINGTON (Reuters) - Robert Mueller, the spe...      1
28898  BRUSSELS (Reuters) - U.S. President Donald Tru...      1
21601  Disney s just doing their part to advance a ra...      0
6593   One night in 2013, Reverend Catherine Brown tu...      0
27561  WASHINGTON (Reuters) - A White House spokesman...      1
41927  WASHINGTON (Reuters) - U.S. Senate Republican ...      1
22297  21st Century Wire says RUSSIA HACK? Still no e...      0
21291  Welcome to the  new America,  where there can ...      0
8066   With marriage equality nationwide, and with mo...      0
28738  WASHINGTON (Reuters) - New U.S. Commerce Secre...      1
4151   Trump campaign manager Kellyanne Conway ran in...      0
35885  BRASILIA (Reuters) - Brazilian President Miche...      1
3944   I am not a psychologist. I don t even play one...      0
37307  GENEVA (Reuters) - The U.N. Human Rights Counc...      1
1375   John Burton, the outgoing chairman of Californ...      0
29322  WASHINGTON (Reuters) - U.S. Defense Secretary ...      1

In [28]:
data.sample(10)

                                                    text  class
13688  One of the countries Mooch and her taxpayer fu...      0
30212  SYDNEY (Reuters) - The United States is ready ...      1
28574  (Reuters) - Highlights of the day for U.S. Pre...      1
25508  WASHINGTON (Reuters) - The Trump administratio...      1
27614  WASHINGTON (Reuters) - The top Republican in t...      1
38443  LONDON (Reuters) - British Foreign Secretary B...      1
39742  VATICAN CITY (Reuters) - Pope Francis, in a ma...      1
11414                                                         0
10294  Lt. Col. Tony Shaffer opened a can of worms to...      0
36026  BOSASO, Somalia (Reuters) - An army colonel in...      1

In [29]:
data["text"] = data["text"].astype(str).apply(clean_text)

In [30]:
data.sample(10)

                                                    text  class
2635   republicans are apparently hellbent on destroy...      0
10047  republican rep steve king the base is going to...      0
30289  washington reuters us senate republican leader...      1
24115  washington reuters the outcome of alabama s de...      1
19064  barack obama is turning his new home in the po...      0
38082  harare reuters zimbabwe president robert mugab...      1
32501  turnberry scotland reuters us presidential can...      1
5196   this was a treat to watchif you want to see a ...      0
19360  obama and his supporters loved talking about h...      0
27073  corrects comey firing to may in fifth paragrap...      1

🔎 What is Training and Testing in Machine Learning?

Training Data

This is the part of the dataset we use to teach the model.

The model looks at the input (text) and the output (class) to learn patterns.

Example:

Input: "Trump wins election" → Output: 1 (True news)

Input: "Aliens attacked the White House" → Output: 0 (Fake news)

By seeing many such examples, the model learns what fake and true news look like.

Testing Data

This is the part of the dataset that the model has never seen before.

We use it to check how well the model performs on new, unseen news.

Example: After training, we give it a new text "Government launches new scheme" → The model predicts if it’s Fake or True.

If the model gets it right most of the time, we know it has learned wel

in below code , We are spitting four parts :

******xtrain (Training Features)*******

These are the input news texts (from "text") used for training the model.
Example: "Government announces new policy" → model will read this.

*******ytrain (Training Labels)*******

These are the correct answers (from "class") for the training inputs.

Example: 1 (True news), 0 (Fake news).

The model uses these labels to learn the relationship between text and class.

*******xtest (Testing Features)*******

These are the input news texts reserved for testing (25% of the data).

The model has never seen these before.

********ytest (Testing Labels)********

These are the correct answers for the testing inputs.

We don’t show these to the model during training.

After training, we compare the model’s predictions with ytest to calculate accuracy, precision, recall, etc.



"xtrain and ytrain are like the practice material for the model: it learns patterns from them.

xtest and ytest are like the final exam: we test the model on new data (xtest) and check if its answers match the real answers (ytest)."

In [31]:
x = data["text"]
y = data["class"]

xtrain, xtest , ytrain, ytest = train_test_split(x,y,test_size=0.25,random_state=42)

using {TF- IDF factorizer}for converting textual data to numerical data ,
 here we create a tfidfvectorizer object

In [32]:
# Replace NaN with empty string
xtrain = xtrain.fillna("")
xtest = xtest.fillna("")

In [33]:
vectorizer = TfidfVectorizer()
xv_train = vectorizer.fit_transform(xtrain)
xv_test = vectorizer.transform(xtest)

In [34]:
data.sample(10)

                                                    text  class
23004  century wire says wikileaks has released its l...      0
35012  melbourne reuters nearly half the people injur...      1
1945   when one votes for someone with a d next to th...      0
33605  washington reuters the white house said on mon...      1
40937  london reuters britain s finance minister phil...      1
10895  donald trump junior was attending a rally when...      0
24580  washington reuters draft legislation respondin...      1
31717  the following timeline charts the origin and s...      1
1175   fox news loves to point the finger at snowflak...      0
34703  washington reuters the us supreme court on tue...      1

In [35]:
lr = LogisticRegression()
lr.fit(xv_train,ytrain)

LogisticRegression()

In [36]:
prediction = lr.predict(xv_test)
lr.score(xv_test,ytest)

0.9862038273253226

In [37]:
print(classification_report(ytest,prediction))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99      5914
           1       0.98      0.99      0.99      5321

    accuracy                           0.99     11235
   macro avg       0.99      0.99      0.99     11235
weighted avg       0.99      0.99      0.99     11235

In [38]:
joblib.dump(vectorizer,"vectorizer.jb")
joblib.dump(lr,"lr_model.jb")

['lr_model.jb']

What You Did in the (nltk.download)+
What you did: You ran a command to download a small data package called punkt.

What it's for: Think of punkt as a "grammar rulebook" for the English language. The TextBlob library (our "mood detector") needs this rulebook to understand how to correctly split articles into sentences and words. It's a necessary, one-time setup that makes sure TextBlob works properly.

In [39]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\DIPTESH\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

# ==============================================================================
#  NEW CODE FOR STEP 1.1: SENTIMENT ANALYSIS
# ==============================================================================

# Make sure to import the TextBlob library at the top of your file


# --- You should have already loaded and concatenated your data into a single 
# --- dataframe called 'data'. We will work with that.

# 1. Define a function to calculate sentiment polarity.
#    The polarity score is a float within the range [-1.0, 1.0].
#    -1.0 means very negative, 0 is neutral, and +1.0 is very positive.

# Create a TextBlob object and return the sentiment polarity
 # Return 0 for any text that might cause an error

 # 2. Apply this function to your 'text' column to create the new feature.
#    This will create a new column named 'sentiment_score'.

# 3. (Optional) Display the first few rows with the new column to verify.

# ==============================================================================
#  END OF NEW CODE FOR STEP 1.1
# ==============================================================================

# Your existing code for defining x and y, and splitting the data would
# come after this. Make sure to include the new feature in 'x'.

# For now, we will continue to use just the 'text' for training, but in a later
# step, we will integrate this new 'sentiment_score' feature into the model.

# ... (the rest of your script continues here)

In [40]:
from textblob import TextBlob

def get_sentiment_polarity(text):
    try:
        
        return TextBlob(text).sentiment.polarity
    except:
       
        return 0


print("Calculating sentiment scores... This may take a moment.")
data['sentiment_score'] = data['text'].apply(get_sentiment_polarity)
print("Sentiment scores calculated.")


print("\nDataFrame with the new 'sentiment_score' feature:")
print(data[['text', 'sentiment_score', 'class']].head())


x = data['text']
y = data['class']

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.25, random_state=42)

Calculating sentiment scores... This may take a moment.
Sentiment scores calculated.

DataFrame with the new 'sentiment_score' feature:
                                                text  sentiment_score  class
0  donald trump just couldn t wish all americans ...         0.073941      0
1  house intelligence committee chairman devin nu...        -0.005004      0
2  on friday it was revealed that former milwauke...        -0.013517      0
3  on christmas day donald trump announced that h...         0.001111      0
4  pope francis used his annual christmas day mes...        -0.011722      0

Step 1.2 : 

The Upgrade: We are replacing our old method (TF-IDF), which is just a word counter, with a powerful "brain" called BERT.

The Job: BERT will read each news article and create a special "meaning barcode" for it.


The Result: This "barcode" is a list of numbers that captures the article's real context and meaning. Using these smart barcodes will make our fake news detector much more accurate


"meaning barcode" in column -> bert_embedding


Inside this column, each news article is now represented by a "meaning barcode"—a list of 768 numbers (a vector).

This barcode is the final, tangible result. You have successfully converted raw, messy text into a clean, intelligent, numerical format that a machine can understand.


#Line 1: tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
What it does: This line downloads the "Instruction Manual" (the Tokenizer).

The job of the tokenizer is to take a normal sentence and translate it into a special numerical code that the BERT "brain" can understand. It breaks words into smaller pieces and converts them into numbers.

The command .from_pretrained means we are downloading a pre-made manual that perfectly matches the brain we are about to get.


#Line 2: model = TFBertModel.from_pretrained('bert-base-uncased', use_safetensors=False)
What it does: This line downloads the actual "Brain" (the TFBertModel).

The command .from_pretrained is the most important part. It tells the program to download a brain that has already been trained for thousands of hours on a massive amount of text from the internet. This is why it's so smart from the start and can give us a "superior understanding of language context".


'bert-base-uncased' is the specific version we're downloading: base is the standard, medium size, and uncased means it treats "The" and "the" as the same word.

use_safetensors=False is the special instruction we added to fix the previous error. It tells the program to download the model in the older, classic file format, which we know works correctly on your system.

In [41]:
import pandas as pd
import tensorflow as tf
from transformers import BertTokenizer, TFBertModel
import numpy as np


print("Loading data...")
df_fake = pd.read_csv("Fake.csv")
df_true = pd.read_csv("True.csv")
df_fake["class"] = 0
df_true["class"] = 1
data = data.sample(frac=1, random_state=42).reset_index(drop=True)
print("Data loaded.")

# 1. Load the pre-trained BERT model and its tokenizer.
print("Loading BERT tokenizer and model...")
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = TFBertModel.from_pretrained('bert-base-uncased', use_safetensors=False)
print("BERT model loaded.")

# 2. Create a function to get the embedding for a single piece of text.
def get_bert_embedding(text):
    text = str(text)
    inputs = tokenizer(text, return_tensors='tf', truncation=True, padding=True, max_length=512)
    outputs = model(inputs)
    embedding = tf.reduce_mean(outputs.last_hidden_state, axis=1)
    return embedding.numpy().flatten()

# 3. CRITICAL: Create a very small sample to test the process.
#    Let's use just 10 articles first.
print("\nCreating a tiny sample of 10 articles to test the embedding process...")
sample_data = data.head(10).copy()

# 4. Apply the function to the sample data.
#    BE PATIENT: Even for 10 articles, this may take several minutes on a CPU.
print("Generating BERT embeddings for the sample... This will be slow.")
sample_data['bert_embedding'] = sample_data['text'].apply(get_bert_embedding)
print("Sample embeddings generated successfully!")

# 5. Display the result to see the new column.
print("\nDataFrame with the new 'bert_embedding' feature:")
print(sample_data[['text', 'bert_embedding', 'class']].head())

c:\Users\DIPTESH\Desktop\PROJECT\newsdetection\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

WARNING:tensorflow:From c:\Users\DIPTESH\Desktop\PROJECT\newsdetection\venv\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Loading data...

C:\Users\DIPTESH\AppData\Local\Temp\ipykernel_10540\1805926431.py:8: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171) have mixed types. Specify dtype option on import or set low_memory=False.
  df_fake = pd.read_csv("Fake.csv")

Data loaded.
Loading BERT tokenizer and model...
WARNING:tensorflow:From c:\Users\DIPTESH\Desktop\PROJECT\newsdetection\venv\Lib\site-packages\tf_keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

TensorFlow and JAX classes are deprecated and will be removed in Transformers v5. We recommend migrating to PyTorch classes or pinning your version of Transformers.
Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.
TensorFlow and JAX classes are deprecated and will be removed in Transformers v5. We recommend migrating to PyTorch classes or pinning your version of Transformers.

BERT model loaded.

Creating a tiny sample of 10 articles to test the embedding process...
Generating BERT embeddings for the sample... This will be slow.
Sample embeddings generated successfully!

DataFrame with the new 'bert_embedding' feature:
                                                text  \
0  century wire says well isn t this interesting ...
1  paris reuters britain is becoming subservient ...
2  american liberal activists still struggling wi...
3  reuters the nuclear regulatory commission said...
4  wow it looks like dem candidate for governor j...

                                      bert_embedding  class
0  [-0.28352213, 0.08793205, 0.12370156, -0.11332...      0
1  [-0.5225939, -0.17693946, 0.29173508, -0.07506...      1
2  [0.0033643567, 0.073747344, 0.44601083, -0.063...      0
3  [-0.36905915, -0.16104957, 0.4080132, 0.102420...      1
4  [-0.37636045, -0.055954847, 0.36282983, 0.1106...      0

 BERT : Bidirectional Encoder Representations from Transformers

BERT is a revolutionary, pre-trained "brain" for understanding human language, developed by Google.
BERT's main superpower is its ability to understand context.

Older models read a sentence from left-to-right or right-to-left. BERT is bidirectional, meaning it reads the entire sentence at once, looking at all the words simultaneously.

basically it is a superpower

How We Are Using It in Our Project:

In our project, we are using BERT's deep understanding of language to perform one specific task:
We feed it a news article.

It reads the entire article, understanding the context of every word.

It then outputs a "meaning barcode" (a contextual embedding) for that article.

In [42]:
# logistic regression

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
import numpy as np


print("Preparing data for the model...")
# 1. Define our features (X) and our labels (y).
#    CORRECTED: Using 'sample_data' which you created in the previous cell.
X = sample_data['bert_embedding']
y = sample_data['class']

# 2. Convert the 'bert_embedding' column into a format scikit-learn can use.
X_stacked = np.vstack(X.values)

# 3. Split the data into a training set and a testing set.
X_train, X_test, y_train, y_test = train_test_split(X_stacked, y, test_size=0.25, random_state=42, stratify=y)
print(f"Data split into {len(X_train)} training samples and {len(X_test)} testing samples.")

# 4. Initialize and train the Logistic Regression model.
print("\nTraining the Logistic Regression model...")
lr_model = LogisticRegression(max_iter=1000) 
lr_model.fit(X_train, y_train)
print("Model training complete.")

# 5. Evaluate the model on the test data.
print("\nEvaluating the model on the test set...")
predictions = lr_model.predict(X_test)

# 6. Print the classification report to see the results with detailed metrics.
print("\nClassification Report:")
print(classification_report(y_test, predictions))

Preparing data for the model...
Data split into 7 training samples and 3 testing samples.

Training the Logistic Regression model...
Model training complete.

Evaluating the model on the test set...

Classification Report:
              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       0.00      0.00      0.00         1

    accuracy                           0.67         3
   macro avg       0.33      0.50      0.40         3
weighted avg       0.44      0.67      0.53         3

c:\Users\DIPTESH\Desktop\PROJECT\newsdetection\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\DIPTESH\Desktop\PROJECT\newsdetection\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\DIPTESH\Desktop\PROJECT\newsdetection\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [43]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

# This code assumes X_train, X_test, y_train, and y_test from the previous step are still in memory.

print("Training the Random Forest model...")
# 1. Initialize the Random Forest model. This is the main change.
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

# 2. Train the model on the same training data.
rf_model.fit(X_train, y_train)
print("Model training complete.")

# 3. Evaluate the model on the same test data.
print("\nEvaluating the model on the test set...")
predictions_rf = rf_model.predict(X_test)

# 4. Print the new classification report to see the results.
print("\nClassification Report (Random Forest):")
print(classification_report(y_test, predictions_rf))

Training the Random Forest model...
Model training complete.

Evaluating the model on the test set...

Classification Report (Random Forest):
              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       0.00      0.00      0.00         1

    accuracy                           0.67         3
   macro avg       0.33      0.50      0.40         3
weighted avg       0.44      0.67      0.53         3

c:\Users\DIPTESH\Desktop\PROJECT\newsdetection\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\DIPTESH\Desktop\PROJECT\newsdetection\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\DIPTESH\Desktop\PROJECT\newsdetection\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [44]:
from xgboost import XGBClassifier
from sklearn.metrics import classification_report

# This code assumes X_train, X_test, y_train, and y_test are still in memory.

print("Training the XGBoost model...")
# 1. Initialize the XGBoost model. This is the main change.
# We add two parameters to prevent common warnings.
xgb_model = XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='logloss')

# 2. Train the model on the same training data.
xgb_model.fit(X_train, y_train)
print("Model training complete.")

# 3. Evaluate the model on the same test data.
print("\nEvaluating the model on the test set...")
predictions_xgb = xgb_model.predict(X_test)

# 4. Print the new classification report to see the results.
print("\nClassification Report (XGBoost):")
print(classification_report(y_test, predictions_xgb))

Training the XGBoost model...
Model training complete.

Evaluating the model on the test set...

Classification Report (XGBoost):
              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       0.00      0.00      0.00         1

    accuracy                           0.67         3
   macro avg       0.33      0.50      0.40         3
weighted avg       0.44      0.67      0.53         3

c:\Users\DIPTESH\Desktop\PROJECT\newsdetection\venv\Lib\site-packages\xgboost\training.py:183: UserWarning: [08:34:45] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\DIPTESH\Desktop\PROJECT\newsdetection\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\DIPTESH\Desktop\PROJECT\newsdetection\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\DIPTESH\Desktop\PROJECT\newsdetection\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [49]:
import pandas as pd
import numpy as np
import tensorflow as tf
from transformers import BertTokenizer, TFBertModel
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

# ==============================================================================
# PART 1: LOAD AND PREPARE DATA
# ==============================================================================
print("Step 1: Loading the 'combined_social_data.csv' dataset...")
# Load the correct dataset
data = pd.read_csv("combined_social_data.csv")

# Ensure the data is shuffled (it should al ready be, but this is good practice)
data = data.sample(frac=1, random_state=42).reset_index(drop=True)
print("Data loaded successfully.")

# ==============================================================================
# PART 2: GENERATE BERT EMBEDDINGS (THE SLOW PART)
# ==============================================================================
print("\nStep 2: Generating BERT embeddings for a 2,000-article sample...")
print("This part will take a significant amount of time. Please be patient.")

# Load BERT model and tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = TFBertModel.from_pretrained('bert-base-uncased', use_safetensors=False)

# Define the embedding function
def get_bert_embedding(text):
    text = str(text)
    inputs = tokenizer(text, return_tensors='tf', truncation=True, padding=True, max_length=512)
    outputs = model(inputs)
    embedding = tf.reduce_mean(outputs.last_hidden_state, axis=1)
    return embedding.numpy().flatten()

# Create the 2,000-article sample from our loaded data
sample_data = data.head(2000).copy()

# Apply the function to generate embeddings
sample_data['bert_embedding'] = sample_data['text'].apply(get_bert_embedding)
print("BERT embeddings generated successfully!")

# ==============================================================================
# PART 3: PREPARE VARIABLES FOR THE MODEL
# ==============================================================================
print("\nStep 3: Preparing the final variables for model training...")
X = sample_data['bert_embedding']
y = sample_data['class']    
X_stacked = np.vstack(X.values)
print("Variables 'X_stacked' and 'y' are now ready.")

# ==============================================================================
# PART 4: HYPERPARAMETER TUNING
# ==============================================================================
print("\nStep 4: Starting hyperparameter tuning...")

# Define the model and parameter grid
model_to_tune = LogisticRegression(max_iter=2000)
param_grid = {
    'C': [0.1, 1, 10, 100],
    'solver': ['liblinear', 'saga']
}

# Set up and run the GridSearchCV
grid_search = GridSearchCV(estimator=model_to_tune, param_grid=param_grid, cv=5, scoring='accuracy', verbose=1)
grid_search.fit(X_stacked, y)
print("Search complete.")

# Print the final results
print("\n-------------------------------------------")
print("Tuning Results:")
print("The best settings found by the search are:")
print(grid_search.best_params_)

print("\nThe best accuracy score achieved with these settings was:")
print(f"{grid_search.best_score_:.4f}")
print("-------------------------------------------")

Step 1: Loading the 'combined_social_data.csv' dataset...
Data loaded successfully.

Step 2: Generating BERT embeddings for a 2,000-article sample...
This part will take a significant amount of time. Please be patient.

Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.

BERT embeddings generated successfully!

Step 3: Preparing the final variables for model training...
Variables 'X_stacked' and 'y' are now ready.

Step 4: Starting hyperparameter tuning...
Fitting 5 folds for each of 8 candidates, totalling 40 fits

c:\Users\DIPTESH\Desktop\PROJECT\newsdetection\venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\DIPTESH\Desktop\PROJECT\newsdetection\venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\DIPTESH\Desktop\PROJECT\newsdetection\venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\DIPTESH\Desktop\PROJECT\newsdetection\venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\DIPTESH\Desktop\PROJECT\newsdetection\venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

Search complete.

-------------------------------------------
Tuning Results:
The best settings found by the search are:
{'C': 10, 'solver': 'liblinear'}

The best accuracy score achieved with these settings was:
0.9995
-------------------------------------------

In [3]:
from sklearn.linear_model import LogisticRegression
from transformers import BertTokenizer
import joblib
import numpy as np

# This code assumes you have 'X_stacked' (the embeddings) and 'y' (the labels)
# from the 2,000-article sample ready in memory.

# 1. Initialize our final, best model with the optimal settings we found from GridSearchCV.
#    The best settings were C=10 and solver='liblinear'.
print("Initializing the final model with the best settings: C=10, solver='liblinear'...")
final_model = LogisticRegression(C=10, solver='liblinear', max_iter=2000)

# 2. Train the final model on the ENTIRE 2,000-article dataset.
#    This gives the model the maximum amount of data to learn from.
print("Training the final model on all 2,000 samples...")
final_model.fit(X_stacked, y)
print("Final model training complete.")

# 3. Save the trained model to a file using joblib.
#    This file is the "brain" that will be loaded by our Streamlit app.
model_filename = 'final_model.joblib'
joblib.dump(final_model, model_filename)
print(f"\nFinal model saved successfully as '{model_filename}'")

# 4. Save the BERT tokenizer again to be safe.
#    This is also needed in our Streamlit app to process user input.
tokenizer_directory = 'bert_tokenizer'
tokenizer.save_pretrained(tokenizer_directory)
print(f"BERT tokenizer saved successfully in the '{tokenizer_directory}' directory.")

Initializing the final model with the best settings: C=10, solver='liblinear'...
Training the final model on all 2,000 samples...
Final model training complete.

Final model saved successfully as 'final_model.joblib'
BERT tokenizer saved successfully in the 'bert_tokenizer' directory.